# Generated by Django 3.2.23 on 2024-03-01 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20240301_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='content_type',
            new_name='item_category',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='object_id',
            new_name='item_id',
        ),
    ]
