# Generated by Django 3.2.23 on 2024-03-13 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20240308_1553'),
        ('auction', '0004_auto_20240301_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='item_category',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='item_id',
        ),
        migrations.AddField(
            model_name='auction',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle'),
            preserve_default=False,
        ),
    ]
