# Generated by Django 3.2.23 on 2024-03-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='buy_now',
            field=models.BooleanField(default=False),
        ),
    ]
