# Generated by Django 3.2.23 on 2024-03-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='user_obj',
        ),
    ]
