# Generated by Django 3.2.23 on 2024-03-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_rename_user_review_user_obj'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
