# Generated by Django 3.2.23 on 2024-02-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('buyer', 'buyer'), ('seller', 'seller')], max_length=255, null=True),
        ),
    ]
