# Generated by Django 3.2.23 on 2024-03-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name'),
        ('users', '0008_userstripe'),
    ]

    operations = [
    ]
